language: generic
before_deploy:
  - chmod +x gradlew
  - ./gradlew build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
